eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  #自定义主机路径
  instance:
    hostname: https://www.lidongshuai.top
spring:
  application:
    name: client
server:
  port: 1060
profiles: dev
auth:
  name: eastcool·Lee
  age: 18
